# -*- coding: utf-8 -*-
"""CPI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1awt83Y6ySPqQ07ZDPSojVIIp01ipUEzh
"""

import pandas as pd
import numpy as np
import requests

"""# Test connection"""

report_series = "CUSR0000SA0L1E" # Core CPI (ex. food and energy); seasonally adjusted 
base_url = 'https://api.bls.gov/publicAPI/v1/timeseries/data/'
series = {'id':report_series,
          'name':"All items less food and energy in U.S. city average, all urban consumers, seasonally adjusted"}
data_url = '{}{}'.format(base_url,series['id'])
print(data_url)

raw_data = requests.get(data_url).json()
print('Status: ' + raw_data['status'])

data = raw_data["Results"]["series"][0]["data"]
data = pd.DataFrame(data[0:14]).drop(["footnotes"], axis = 1)
data["period"] = data["period"].map(lambda x: x.lstrip("M"))
data["value"] = pd.to_numeric(data["value"])
data["chg"] = np.round(data["value"].pct_change(periods = -1) * 100, 1)
data = data[0:13]
data

def CPI_statement():
  change_mom = round(data["chg"][0] - data["chg"][1], 1)
  if data["chg"][0] > data["chg"][1]:
    print("Headline {} CPI was up {}pp m/m to {}%".format(data["periodName"][0],abs(change_mom), data["chg"][0]))
  elif data["chg"][0] < data["chg"][1]:
    print("Headline {} CPI was down {}pp m/m to {}%".format(data["periodName"][0],abs(change_mom), data["chg"][0]))
  else:
    print("Headline {} CPI was unchanged m/m at {}%".format(data["periodName"][0], data["chg"][0]))

CPI_statement()



